// App.cpp — Spatial Root ImGui + GLFW desktop GUI application implementation.
//
// Feature parity target: gui/realtimeGUI/ (Python PySide6 GUI).
// Controls the engine via direct C++ API calls (EngineSession setters) rather
// than OSC, matching the Stage 2 embedding architecture.

#include "App.hpp"
#include "FileDialog.hpp"
#include "imgui_stdlib.h"    // ImGui::InputText with std::string

#include <al/io/al_AudioIO.hpp>

#include <GLFW/glfw3.h>
#include "stb_image.h"
#include "miniLogo_data.h"  // embedded PNG bytes — generated by xxd at build time

#include <filesystem>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <sstream>

namespace fs = std::filesystem;

// ── Static constants (out-of-class definitions) ───────────────────────────────
constexpr int         App::kBufferSizes[];
constexpr const char* App::kBufferSizeNames[];
constexpr const char* App::kLayoutNames[];
constexpr const char* App::kLayoutPaths[];
constexpr const char* App::kElevModeNames[];
constexpr const char* App::kTcFormatNames[];
constexpr const char* App::kTcFormatValues[];
constexpr const char* App::kTcLfeModeNames[];
constexpr const char* App::kTcLfeModeValues[];

// ── Constructor / Destructor ──────────────────────────────────────────────────

App::App(std::string projectRoot)
    : mProjectRoot(std::move(projectRoot))
    , mSession(std::make_unique<EngineSession>())
{
    // Pre-populate layout path from the default preset
    mLayoutPath = resolveProjectPath(kLayoutPaths[0]);

    appendEngineLog("[GUI] Spatial Root — ImGui + GLFW GUI started.");
    appendEngineLog("[GUI] Project root: " + mProjectRoot);
    appendEngineLog("[GUI] Select a source and layout, then click START.");

    // Load logo image as OpenGL texture from embedded PNG bytes (miniLogo_data.h).
    // Using stbi_load_from_memory avoids any runtime path lookup — works regardless
    // of the working directory (Finder launch, run.sh, etc.).
    // Requires an active GL context — guaranteed: App is constructed after
    // glfwMakeContextCurrent() in main.cpp. Falls back to ⊙ symbol on failure.
    int lw = 0, lh = 0, lch = 0;
    unsigned char* logoData = stbi_load_from_memory(
        miniLogo_png, (int)miniLogo_png_len, &lw, &lh, &lch, 4);
    if (logoData) {
        glGenTextures(1, &mLogoTexId);
        glBindTexture(GL_TEXTURE_2D, mLogoTexId);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, lw, lh, 0, GL_RGBA, GL_UNSIGNED_BYTE, logoData);
        glBindTexture(GL_TEXTURE_2D, 0);
        stbi_image_free(logoData);
    }
}

App::~App() {
    requestShutdown();
    if (mLogoTexId != 0) {
        glDeleteTextures(1, &mLogoTexId);
        mLogoTexId = 0;
    }
}

// ── tick() — called once per render frame ─────────────────────────────────────

void App::tick() {
    tickEngine();
    renderUI();
}

void App::tickEngine() {
    // Poll the running engine
    if (mState == AppState::Running || mState == AppState::Paused) {
        mStatus = mSession->queryStatus();
        mSession->update();

        DiagnosticEvents ev = mSession->consumeDiagnostics();

        // Log diagnostic events
        char buf[256];
        if (ev.renderRelocEvent) {
            snprintf(buf, sizeof(buf),
                "[RELOC-RENDER]  t=%.1fs  0x%llx → 0x%llx",
                mStatus.timeSec,
                (unsigned long long)ev.renderRelocPrev,
                (unsigned long long)ev.renderRelocNext);
            appendEngineLog(buf, {0.7f, 0.7f, 1.f, 1.f});
        }
        if (ev.deviceRelocEvent) {
            snprintf(buf, sizeof(buf),
                "[RELOC-DEVICE]  t=%.1fs  0x%llx → 0x%llx",
                mStatus.timeSec,
                (unsigned long long)ev.deviceRelocPrev,
                (unsigned long long)ev.deviceRelocNext);
            appendEngineLog(buf, {0.7f, 0.7f, 1.f, 1.f});
        }
        if (ev.renderDomRelocEvent && mStatus.mainRms > 0.005f) {
            snprintf(buf, sizeof(buf),
                "[DOM-RENDER]    t=%.1fs  0x%llx → 0x%llx",
                mStatus.timeSec,
                (unsigned long long)ev.renderDomRelocPrev,
                (unsigned long long)ev.renderDomRelocNext);
            appendEngineLog(buf, {0.6f, 0.8f, 1.f, 1.f});
        }
        if (ev.renderClusterEvent && mStatus.mainRms > 0.005f) {
            snprintf(buf, sizeof(buf),
                "[CLUSTER-RENDER] t=%.1fs  0x%llx → 0x%llx",
                mStatus.timeSec,
                (unsigned long long)ev.renderClusterPrev,
                (unsigned long long)ev.renderClusterNext);
            appendEngineLog(buf, {0.6f, 0.8f, 1.f, 1.f});
        }

        // Device loss / exit request
        if (mStatus.isExitRequested) {
            appendEngineLog("[Engine] Exit requested (device loss?). Shutting down.",
                            {1.f, 0.5f, 0.2f, 1.f});
            mSession->shutdown();
            mState = AppState::Idle;
        }

        // Sync pause state
        if (mStatus.paused && mState == AppState::Running)
            mState = AppState::Paused;
        else if (!mStatus.paused && mState == AppState::Paused)
            mState = AppState::Running;
    }

    // Check if ADM transcoder finished
    if (mState == AppState::Transcoding && !mTranscoder.isRunning()) {
        int code = mTranscoder.exitCode();
        if (code == 0) {
            appendEngineLog("[Transcoder] Complete. Launching engine...",
                            {0.3f, 0.9f, 0.3f, 1.f});
            doLaunchEngine(mTranscodeScene, "", mTranscodeAdm);
        } else {
            mLastError = "cult-transcoder exited with code " + std::to_string(code);
            appendEngineLog("[Transcoder] FAILED: " + mLastError, {1.f, 0.3f, 0.3f, 1.f});
            mState = AppState::Error;
        }
    }

    // Check if standalone transcode panel runner finished
    bool tcWasRunning = mTcRunning;
    mTcRunning = mTcRunner.isRunning();
    if (tcWasRunning && !mTcRunning) {
        mTcDone    = true;
        mTcSuccess = (mTcRunner.exitCode() == 0);
    }
}

// ── requestShutdown() ─────────────────────────────────────────────────────────

void App::requestShutdown() {
    if (mShutdownRequested) return;
    mShutdownRequested = true;
    if (mState == AppState::Running || mState == AppState::Paused) {
        appendEngineLog("[GUI] Shutting down engine...");
        mSession->shutdown();
        mState = AppState::Idle;
    }
}

// ── renderUI() ────────────────────────────────────────────────────────────────

void App::renderUI() {
    ImGuiIO& io = ImGui::GetIO();
    ImGui::SetNextWindowPos({0.f, 0.f});
    ImGui::SetNextWindowSize(io.DisplaySize);
    ImGui::Begin("##root", nullptr,
        ImGuiWindowFlags_NoTitleBar  |
        ImGuiWindowFlags_NoResize    |
        ImGuiWindowFlags_NoMove      |
        ImGuiWindowFlags_NoBringToFrontOnFocus);

    // ── Header bar ────────────────────────────────────────────────────────
    ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 2.f);

    // Logo image (left) — ⊙ symbol fallback if texture failed to load
    float logoH = ImGui::GetTextLineHeight();
    if (mLogoTexId != 0) {
        ImGui::Image((ImTextureID)(intptr_t)mLogoTexId, ImVec2(logoH, logoH));
    } else {
        ImGui::TextColored({0.60f, 0.57f, 0.52f, 1.f}, "⊙");
    }
    ImGui::SameLine(0.f, 8.f);
    ImGui::Text("Spatial Root");
    ImGui::SameLine(0.f, 6.f);
    ImGui::TextDisabled("Real-Time Engine");

    // Workflow breadcrumb (centre) — skip if window too narrow to avoid collision
    float leftEnd = ImGui::GetItemRectMax().x;  // right edge of last left-side item
    const char* crumb = "ADM  →  LUSID  →  Spatial Render";
    float crumbW = ImGui::CalcTextSize(crumb).x;
    float crumbX = (ImGui::GetWindowWidth() - crumbW) * 0.5f;
    if (crumbX > leftEnd + 8.f) {
        ImGui::SameLine(crumbX);
        ImGui::TextDisabled("%s", crumb);
    }

    // State indicator (right)
    char stateBuf[64];
    snprintf(stateBuf, sizeof(stateBuf), "●  %s", stateName(mState));
    float stateW = ImGui::CalcTextSize(stateBuf).x + 16.f;
    ImGui::SameLine(ImGui::GetWindowWidth() - stateW);
    ImGui::TextColored(stateColor(mState), "%s", stateBuf);

    ImGui::Separator();

    // ── Tabs ──────────────────────────────────────────────────────────────
    if (ImGui::BeginTabBar("##tabs")) {
        if (ImGui::BeginTabItem("ENGINE")) {
            renderEngineTab();
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("TRANSCODE")) {
            renderTranscodeTab();
            ImGui::EndTabItem();
        }
        ImGui::EndTabBar();
    }

    ImGui::End();
}

// ── renderEngineTab() ─────────────────────────────────────────────────────────
// Each section is a bordered card (BeginChild with border=true).
// Heights are sized to fit content at 13.5px Menlo font with the current style.
// Card gap is one Spacing() call between cards.

void App::renderEngineTab() {
    bool isRunning = (mState == AppState::Running || mState == AppState::Paused);
    bool isIdle    = (mState == AppState::Idle || mState == AppState::Error);

    // Muted green for detected source type
    const ImVec4 kGreen  = {0.20f, 0.62f, 0.25f, 1.f};
    // Amber for busy/transcoding
    const ImVec4 kAmber  = {0.70f, 0.45f, 0.08f, 1.f};
    // Red for errors
    const ImVec4 kRed    = {0.72f, 0.18f, 0.15f, 1.f};

    // ── INPUT CONFIGURATION card ──────────────────────────────────────────
    // 5 widget rows + card label + spacing + source hint line ≈ 206px
    if (ImGui::BeginChild("##inputcard", {0.f, 206.f}, true)) {
        ImGui::TextDisabled("INPUT CONFIGURATION");
        ImGui::Spacing();

        if (isRunning) ImGui::BeginDisabled(true);

        // Source
        ImGui::TextDisabled("SOURCE");
        if (mSourceIsAdm)        { ImGui::SameLine(); ImGui::TextColored(kGreen, "ADM"); }
        else if (mSourceIsLusid) { ImGui::SameLine(); ImGui::TextColored(kGreen, "LUSID"); }
        ImGui::SameLine(120.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 78.f);
        if (ImGui::InputText("##source", &mSourcePath)) detectSource();
        ImGui::SameLine();
        if (ImGui::Button("Browse##src")) {
            std::string p = pickFileOrDirectory("Select Audio Source");
            if (!p.empty()) { mSourcePath = p; detectSource(); }
        }

        // Source hint — feedback shown when mSourceHint is populated by detectSource()
        if (!mSourceHint.empty()) {
            bool isError = !mSourceIsAdm && !mSourceIsLusid;
            ImGui::SetCursorPosX(120.f);
            ImGui::TextColored(isError ? kRed : kGreen, "%s", mSourceHint.c_str());
        }

        // Speaker layout
        ImGui::TextDisabled("LAYOUT");
        ImGui::SameLine(120.f);
        ImGui::SetNextItemWidth(110.f);
        if (ImGui::Combo("##layoutpreset", &mLayoutPreset, kLayoutNames, 3)) {
            if (mLayoutPreset < 2)
                mLayoutPath = resolveProjectPath(kLayoutPaths[mLayoutPreset]);
        }
        ImGui::SameLine();
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 78.f);
        ImGui::InputText("##layout", &mLayoutPath);
        ImGui::SameLine();
        if (ImGui::Button("Browse##layout")) {
            std::string p = pickFile("Select Speaker Layout", {"*.json"}, "JSON files");
            if (!p.empty()) { mLayoutPath = p; mLayoutPreset = 2; }
        }

        // Remap CSV
        ImGui::TextDisabled("REMAP CSV");
        ImGui::SameLine(120.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 78.f);
        ImGui::InputText("##remap", &mRemapPath);
        ImGui::SameLine();
        if (ImGui::Button("Browse##remap")) {
            std::string p = pickFile("Select Remap CSV", {"*.csv"}, "CSV files");
            if (!p.empty()) mRemapPath = p;
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("optional — leave blank to disable channel remapping");

        // Device
        ImGui::TextDisabled("DEVICE");
        ImGui::SameLine(120.f);
        if (ImGui::Button("Scan##device")) scanDevices();
        ImGui::SameLine();
        if (mDeviceList.empty()) {
            ImGui::TextDisabled("(click Scan to list output devices)");
        } else {
            std::vector<const char*> items;
            for (const auto& d : mDeviceList) items.push_back(d.c_str());
            ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 8.f);
            if (ImGui::Combo("##device", &mDeviceIdx, items.data(), (int)items.size()))
                mDeviceName = (mDeviceIdx == 0) ? "" : mDeviceList[mDeviceIdx];
        }

        // Buffer size
        ImGui::TextDisabled("BUFFER");
        ImGui::SameLine(120.f);
        ImGui::SetNextItemWidth(100.f);
        ImGui::Combo("##bufsize", &mBufferSizeIdx, kBufferSizeNames, 5);

        if (isRunning) ImGui::EndDisabled();
    }
    ImGui::EndChild();
    ImGui::Spacing();

    // ── TRANSPORT card ────────────────────────────────────────────────────
    // Buttons + status line + optional error/busy line ≈ 108px
    if (ImGui::BeginChild("##transportcard", {0.f, 108.f}, true)) {
        ImGui::TextDisabled("TRANSPORT");
        ImGui::Spacing();

        bool canStart  = isIdle;
        bool canStop   = isRunning;
        bool canPause  = (mState == AppState::Running);
        bool canResume = (mState == AppState::Paused);
        bool busy      = (mState == AppState::Transcoding);

        if (!canStart) ImGui::BeginDisabled(true);
        if (ImGui::Button("Start"))  onStart();
        if (!canStart) ImGui::EndDisabled();

        ImGui::SameLine();
        if (!canStop) ImGui::BeginDisabled(true);
        if (ImGui::Button("Stop"))   onStop();
        if (!canStop) ImGui::EndDisabled();

        ImGui::SameLine();
        if (!canPause) ImGui::BeginDisabled(true);
        if (ImGui::Button("Pause"))  onPause();
        if (!canPause) ImGui::EndDisabled();

        ImGui::SameLine();
        if (!canResume) ImGui::BeginDisabled(true);
        if (ImGui::Button("Resume")) onResume();
        if (!canResume) ImGui::EndDisabled();

        // State badge (right-aligned)
        const char* badge    = stateName(mState);
        float       badgeW   = ImGui::CalcTextSize(badge).x + 20.f;
        ImGui::SameLine(ImGui::GetContentRegionAvail().x + ImGui::GetCursorPosX() - badgeW);
        ImGui::TextColored(stateColor(mState), "●  %s", badge);

        // Second row: status (running) / busy / error
        if (isRunning) {
            ImGui::Text("t=%.1fs", mStatus.timeSec);
            ImGui::SameLine();
            ImGui::Text("CPU=%.1f%%", mStatus.cpuLoad * 100.f);
            ImGui::SameLine();
            ImGui::Text("RMS=%.4f", mStatus.mainRms);
            ImGui::SameLine();
            ImGui::Text("Xrun=%zu", mStatus.xruns);
            if (mStatus.nanGuardCount > 0 || mStatus.speakerProximityCount > 0) {
                ImGui::SameLine();
                ImGui::TextColored(kAmber, "NaN=%llu Prox=%llu",
                    (unsigned long long)mStatus.nanGuardCount,
                    (unsigned long long)mStatus.speakerProximityCount);
            }
        } else if (busy) {
            ImGui::TextColored(kAmber, "Transcoding ADM...");
        } else if (mState == AppState::Error && !mLastError.empty()) {
            ImGui::TextColored(kRed, "Error: %s", mLastError.c_str());
        }
    }
    ImGui::EndChild();
    ImGui::Spacing();

    // ── RUNTIME CONTROLS card ─────────────────────────────────────────────
    // 4 slider rows + checkbox + elevation combo + label ≈ 220px
    if (ImGui::BeginChild("##ctrlcard", {0.f, 220.f}, true)) {
        ImGui::TextDisabled("RUNTIME CONTROLS");
        ImGui::Spacing();

        if (!isRunning) ImGui::BeginDisabled(true);

        // Master Gain
        ImGui::TextDisabled("MASTER GAIN");
        ImGui::SameLine(160.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 70.f);
        if (ImGui::SliderFloat("##gain", &mGain, 0.1f, 3.0f, "%.2f"))
            if (isRunning) mSession->setMasterGain(mGain);
        ImGui::SameLine();
        ImGui::SetNextItemWidth(60.f);
        if (ImGui::InputFloat("##gaininput", &mGain, 0.f, 0.f, "%.2f"))
            if (isRunning) { mGain = std::clamp(mGain, 0.1f, 3.0f); mSession->setMasterGain(mGain); }

        // DBAP Focus
        ImGui::TextDisabled("DBAP FOCUS");
        ImGui::SameLine(160.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 70.f);
        if (ImGui::SliderFloat("##focus", &mFocus, 0.2f, 5.0f, "%.2f"))
            if (isRunning) mSession->setDbapFocus(mFocus);
        ImGui::SameLine();
        ImGui::SetNextItemWidth(60.f);
        if (ImGui::InputFloat("##focusinput", &mFocus, 0.f, 0.f, "%.2f"))
            if (isRunning) { mFocus = std::clamp(mFocus, 0.2f, 5.0f); mSession->setDbapFocus(mFocus); }

        // Speaker Mix dB
        ImGui::TextDisabled("SPEAKER MIX (DB)");
        ImGui::SameLine(160.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 70.f);
        if (ImGui::SliderFloat("##spkmix", &mSpkMixDb, -10.f, 10.f, "%.1f dB"))
            if (isRunning) mSession->setSpeakerMixDb(mSpkMixDb);
        ImGui::SameLine();
        ImGui::SetNextItemWidth(60.f);
        if (ImGui::InputFloat("##spkmixinput", &mSpkMixDb, 0.f, 0.f, "%.1f"))
            if (isRunning) { mSpkMixDb = std::clamp(mSpkMixDb, -10.f, 10.f); mSession->setSpeakerMixDb(mSpkMixDb); }

        // Sub Mix dB
        ImGui::TextDisabled("SUB MIX (DB)");
        ImGui::SameLine(160.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 70.f);
        if (ImGui::SliderFloat("##submix", &mSubMixDb, -10.f, 10.f, "%.1f dB"))
            if (isRunning) mSession->setSubMixDb(mSubMixDb);
        ImGui::SameLine();
        ImGui::SetNextItemWidth(60.f);
        if (ImGui::InputFloat("##submixinput", &mSubMixDb, 0.f, 0.f, "%.1f"))
            if (isRunning) { mSubMixDb = std::clamp(mSubMixDb, -10.f, 10.f); mSession->setSubMixDb(mSubMixDb); }

        // Auto Compensation
        if (ImGui::Checkbox("FOCUS AUTO-COMPENSATION", &mAutoComp))
            if (isRunning) mSession->setAutoCompensation(mAutoComp);

        // Elevation Mode
        ImGui::TextDisabled("ELEVATION MODE");
        ImGui::SameLine(160.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 8.f);
        if (ImGui::Combo("##elevmode", &mElevationMode, kElevModeNames, 3))
            if (isRunning) mSession->setElevationMode(static_cast<ElevationMode>(mElevationMode));

        if (!isRunning) ImGui::EndDisabled();
    }
    ImGui::EndChild();
    ImGui::Spacing();

    // ── ENGINE LOG card (fills remaining space) ───────────────────────────
    float logH = ImGui::GetContentRegionAvail().y;
    if (ImGui::BeginChild("##logcard", {0.f, logH}, true)) {
        ImGui::TextDisabled("ENGINE LOG");
        ImGui::Spacing();
        if (ImGui::BeginChild("##enginelog",
                {0.f, ImGui::GetContentRegionAvail().y},
                false,
                ImGuiWindowFlags_HorizontalScrollbar)) {
            for (const auto& entry : mEngineLog) {
                ImGui::TextColored(entry.color, "%s", entry.text.c_str());
            }
            if (mEngineLogAutoScroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY() - 20.f)
                ImGui::SetScrollHereY(1.f);
        }
        ImGui::EndChild();
    }
    ImGui::EndChild();
}

// ── renderTranscodeTab() ──────────────────────────────────────────────────────

void App::renderTranscodeTab() {
    const ImVec4 kGreen = {0.20f, 0.62f, 0.25f, 1.f};
    const ImVec4 kAmber = {0.70f, 0.45f, 0.08f, 1.f};
    const ImVec4 kRed   = {0.72f, 0.18f, 0.15f, 1.f};

    bool tcBusy = mTcRunner.isRunning();

    // ── TRANSCODE CONFIGURATION card ──────────────────────────────────────
    // 4 widget rows + label + spacing ≈ 162px
    if (ImGui::BeginChild("##tcconfigcard", {0.f, 162.f}, true)) {
        ImGui::TextDisabled("TRANSCODE CONFIGURATION");
        ImGui::Spacing();

        if (tcBusy) ImGui::BeginDisabled(true);

        // Input file
        ImGui::TextDisabled("INPUT FILE");
        ImGui::SameLine(130.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 78.f);
        ImGui::InputText("##tcinput", &mTcInput);
        ImGui::SameLine();
        if (ImGui::Button("Browse##tcinput")) {
            std::string p = pickFile("Select ADM Input", {"*.wav", "*.xml"}, "ADM files");
            if (!p.empty()) mTcInput = p;
        }

        // In-format override
        ImGui::TextDisabled("IN-FORMAT");
        ImGui::SameLine(130.f);
        ImGui::SetNextItemWidth(140.f);
        ImGui::Combo("##tcinformat", &mTcInFormat, kTcFormatNames, 4);

        // LFE mode
        ImGui::TextDisabled("LFE MODE");
        ImGui::SameLine(130.f);
        ImGui::SetNextItemWidth(140.f);
        ImGui::Combo("##tclfemode", &mTcLfeMode, kTcLfeModeNames, 2);

        // Output path
        ImGui::TextDisabled("OUTPUT");
        ImGui::SameLine(130.f);
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 8.f);
        ImGui::InputText("##tcoutput", &mTcOutput);
        ImGui::SameLine(130.f);
        ImGui::TextDisabled("(empty = auto-derived from input path)");

        if (tcBusy) ImGui::EndDisabled();
    }
    ImGui::EndChild();
    ImGui::Spacing();

    // ── TRANSCODE CONTROL card ─────────────────────────────────────────────
    // Button row + status line ≈ 80px
    if (ImGui::BeginChild("##tcctrlcard", {0.f, 80.f}, true)) {
        ImGui::TextDisabled("CONTROL");
        ImGui::Spacing();

        if (tcBusy) ImGui::BeginDisabled(true);
        if (ImGui::Button("Transcode", {120.f, 0.f})) {
        // Resolve format (auto = infer from extension)
        std::string format = kTcFormatValues[mTcInFormat];
        if (mTcInFormat == 0) {
            // Auto-detect from extension
            std::string lower = mTcInput;
            std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
            if (lower.size() > 4 && lower.substr(lower.size() - 4) == ".wav")
                format = "adm_wav";
            else if (lower.size() > 4 && lower.substr(lower.size() - 4) == ".xml")
                format = "adm_xml";
            else
                format = "adm_wav";  // safe default
        }

        // Resolve output path
        std::string outPath = mTcOutput;
        if (outPath.empty() && !mTcInput.empty()) {
            fs::path p(mTcInput);
            outPath = (p.parent_path() / (p.stem().string() + ".lusid.json")).string();
        }

        std::string cultBin = findCultTranscoder();
        if (cultBin.empty()) {
            appendTcLog("[error] cult-transcoder binary not found. Build with ./build.sh first.");
        } else if (mTcInput.empty()) {
            appendTcLog("[error] Input path is required.");
        } else {
            mTcDone = false;
            mTcSuccess = false;
            mTcRunning = true;

            // Derive report path
            fs::path op(outPath);
            std::string reportPath = (op.parent_path() /
                (op.stem().string() + "_report.json")).string();

            // Create output directory
            try { fs::create_directories(op.parent_path()); } catch (...) {}

            std::vector<std::string> args = {
                cultBin,
                "transcode",
                "--in",         mTcInput,
                "--in-format",  format,
                "--out",        outPath,
                "--out-format", "lusid_json",
                "--report",     reportPath,
                "--lfe-mode",   kTcLfeModeValues[mTcLfeMode],
            };
            appendTcLog("[GUI] Running: " + cultBin + " transcode ...");

            mTcRunner.start(args, [this](const std::string& line) {
                appendTcLog(line);
            });
        }
    }
        if (tcBusy) ImGui::EndDisabled();

        // Status right-aligned
        const char* tcStatus = tcBusy ? "Running..." :
                               mTcDone ? (mTcSuccess ? "Complete" : "Failed") : "Idle";
        ImVec4 tcColor = tcBusy ? kAmber :
                         mTcDone ? (mTcSuccess ? kGreen : kRed) :
                         ImGui::GetStyleColorVec4(ImGuiCol_TextDisabled);
        float statusW = ImGui::CalcTextSize(tcStatus).x + 20.f;
        ImGui::SameLine(ImGui::GetContentRegionAvail().x + ImGui::GetCursorPosX() - statusW);
        ImGui::TextColored(tcColor, "●  %s", tcStatus);
    }
    ImGui::EndChild();
    ImGui::Spacing();

    // ── TRANSCODE LOG card (fills remaining space) ─────────────────────────
    float logH = ImGui::GetContentRegionAvail().y;
    if (ImGui::BeginChild("##tclogcard", {0.f, logH}, true)) {
        ImGui::TextDisabled("TRANSCODE LOG");
        ImGui::Spacing();

        // Copy log under lock so the background thread can append freely during render.
        std::deque<LogEntry> tcLogSnapshot;
        {
            std::lock_guard<std::mutex> lock(mTcLogMutex);
            tcLogSnapshot = mTcLog;
        }
        if (ImGui::BeginChild("##tclog",
                {0.f, ImGui::GetContentRegionAvail().y},
                false,
                ImGuiWindowFlags_HorizontalScrollbar)) {
            for (const auto& entry : tcLogSnapshot) {
                ImGui::TextColored(entry.color, "%s", entry.text.c_str());
            }
            if (mTcLogAutoScroll &&
                ImGui::GetScrollY() >= ImGui::GetScrollMaxY() - 20.f)
                ImGui::SetScrollHereY(1.f);
        }
        ImGui::EndChild();
    }
    ImGui::EndChild();
}

// ── Engine lifecycle ──────────────────────────────────────────────────────────

void App::onStart() {
    if (mSourcePath.empty()) {
        mLastError = "Source path is required.";
        mState = AppState::Error;
        appendEngineLog("[GUI] Cannot start: " + mLastError, {1.f, 0.4f, 0.4f, 1.f});
        return;
    }
    if (mLayoutPath.empty()) {
        mLastError = "Layout path is required.";
        mState = AppState::Error;
        appendEngineLog("[GUI] Cannot start: " + mLastError, {1.f, 0.4f, 0.4f, 1.f});
        return;
    }

    detectSource();

    if (!mSourceIsAdm && !mSourceIsLusid) {
        mLastError = "Source must be an ADM WAV file or a LUSID package directory (containing scene.lusid.json).";
        mState = AppState::Error;
        appendEngineLog("[GUI] Cannot start: " + mLastError, {1.f, 0.4f, 0.4f, 1.f});
        return;
    }

    // Reset controls to defaults on each new start (mirrors Python GUI behaviour)
    resetRuntimeToDefaults();
    mLastError.clear();

    if (mSourceIsAdm) {
        // ADM WAV → run cult-transcoder first
        std::string cultBin = findCultTranscoder();
        if (cultBin.empty()) {
            mLastError = "cult-transcoder binary not found. Build with ./build.sh first.";
            mState = AppState::Error;
            appendEngineLog("[GUI] " + mLastError, {1.f, 0.4f, 0.4f, 1.f});
            return;
        }

        mTranscodeAdm   = mSourcePath;
        mTranscodeScene = transcodeOutputPath(mSourcePath);

        // Create output directory
        try {
            fs::create_directories(fs::path(mTranscodeScene).parent_path());
        } catch (...) {}

        fs::path sp(mTranscodeScene);
        std::string reportPath = (sp.parent_path() /
            (sp.stem().string() + "_report.json")).string();

        std::vector<std::string> args = {
            cultBin,
            "transcode",
            "--in",         mTranscodeAdm,
            "--in-format",  "adm_wav",
            "--out",        mTranscodeScene,
            "--out-format", "lusid_json",
            "--report",     reportPath,
            "--lfe-mode",   "hardcoded",
        };

        appendEngineLog("[GUI] ADM source detected. Running cult-transcoder...",
                        {1.f, 0.8f, 0.2f, 1.f});
        mState = AppState::Transcoding;

        mTranscoder.start(args, [this](const std::string& line) {
            appendEngineLog("[transcoder] " + line);
        });

    } else {
        // LUSID package — find scene.lusid.json
        std::string scenePath = (fs::path(mSourcePath) / "scene.lusid.json").string();
        doLaunchEngine(scenePath, mSourcePath, "");
    }
}

void App::onStop() {
    if (mState == AppState::Running || mState == AppState::Paused) {
        appendEngineLog("[GUI] Stopping engine...");
        mSession->shutdown();
        mState = AppState::Idle;
        appendEngineLog("[GUI] Engine stopped.");
    }
}

void App::onPause() {
    if (mState == AppState::Running) {
        mSession->setPaused(true);
        mState = AppState::Paused;
        appendEngineLog("[GUI] Paused.");
    }
}

void App::onResume() {
    if (mState == AppState::Paused) {
        mSession->setPaused(false);
        mState = AppState::Running;
        appendEngineLog("[GUI] Resumed.");
    }
}

void App::doLaunchEngine(const std::string& scenePath,
                          const std::string& sourcesFolder,
                          const std::string& admFile) {
    mSession = std::make_unique<EngineSession>();
    appendEngineLog("[GUI] Configuring engine...");

    EngineOptions opts;
    opts.sampleRate    = 48000;
    opts.bufferSize    = kBufferSizes[mBufferSizeIdx];
    opts.outputDeviceName = mDeviceName;
    opts.oscPort       = 9009;  // OSC enabled by default (see App.hpp DEV NOTE)
    opts.elevationMode = ElevationMode::RescaleAtmosUp;

    if (!mSession->configureEngine(opts)) {
        mLastError = mSession->getLastError();
        mState = AppState::Error;
        appendEngineLog("[Engine] configureEngine failed: " + mLastError, {1.f,0.4f,0.4f,1.f});
        return;
    }

    SceneInput scene;
    scene.scenePath     = scenePath;
    scene.sourcesFolder = sourcesFolder;
    scene.admFile       = admFile;

    if (!mSession->loadScene(scene)) {
        mLastError = mSession->getLastError();
        mState = AppState::Error;
        appendEngineLog("[Engine] loadScene failed: " + mLastError, {1.f,0.4f,0.4f,1.f});
        mSession->shutdown();
        return;
    }

    LayoutInput layout;
    layout.layoutPath   = mLayoutPath;
    layout.remapCsvPath = mRemapPath;

    if (!mSession->applyLayout(layout)) {
        mLastError = mSession->getLastError();
        mState = AppState::Error;
        appendEngineLog("[Engine] applyLayout failed: " + mLastError, {1.f,0.4f,0.4f,1.f});
        mSession->shutdown();
        return;
    }

    RuntimeParams rp;
    rp.masterGain       = mGain;
    rp.dbapFocus        = mFocus;
    rp.speakerMixDb     = mSpkMixDb;
    rp.subMixDb         = mSubMixDb;
    rp.autoCompensation = mAutoComp;

    if (!mSession->configureRuntime(rp)) {
        mLastError = mSession->getLastError();
        mState = AppState::Error;
        appendEngineLog("[Engine] configureRuntime failed: " + mLastError, {1.f,0.4f,0.4f,1.f});
        mSession->shutdown();
        return;
    }

    if (!mSession->start()) {
        mLastError = mSession->getLastError();
        mState = AppState::Error;
        appendEngineLog("[Engine] start() failed: " + mLastError, {1.f,0.4f,0.4f,1.f});
        mSession->shutdown();
        return;
    }

    // Apply elevation mode (start() uses ElevationMode::RescaleAtmosUp from opts;
    // if the user has changed the combo, sync it now via the V1.1 setter)
    mSession->setElevationMode(static_cast<ElevationMode>(mElevationMode));

    mState = AppState::Running;
    appendEngineLog("[Engine] Started successfully. OSC port 9009.",
                    {0.3f, 0.9f, 0.3f, 1.f});
}

void App::resetRuntimeToDefaults() {
    mGain          = 0.5f;
    mFocus         = 1.5f;
    mSpkMixDb      = 0.0f;
    mSubMixDb      = 0.0f;
    mAutoComp      = false;
    mElevationMode = 0;
}

// ── Device scanning ───────────────────────────────────────────────────────────

void App::scanDevices() {
    mDeviceList.clear();
    mDeviceList.push_back("(system default)");

    int n = al::AudioDevice::numDevices();
    for (int i = 0; i < n; ++i) {
        al::AudioDevice dev(i);
        if (dev.valid() && dev.hasOutput())
            mDeviceList.push_back(std::string(dev.name()));
    }

    // Keep selection valid; reset to system default after each scan.
    mDeviceIdx = 0;
    mDeviceName = "";
}

// ── Source detection ──────────────────────────────────────────────────────────

void App::detectSource() {
    mSourceIsAdm   = false;
    mSourceIsLusid = false;
    mSourceHint    = "";

    if (mSourcePath.empty()) return;

    std::error_code ec;
    fs::path p(mSourcePath);

    if (!fs::exists(p, ec)) {
        mSourceHint = "Path does not exist";
        return;
    }

    if (fs::is_regular_file(p, ec)) {
        std::string ext = p.extension().string();
        std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
        if (ext == ".wav") {
            mSourceIsAdm = true;
            mSourceHint  = "Detected: ADM WAV";
        } else {
            mSourceHint = "Unrecognized file type — expected .wav (ADM)";
        }
    } else if (fs::is_directory(p, ec)) {
        fs::path scene = p / "scene.lusid.json";
        if (fs::exists(scene, ec)) {
            mSourceIsLusid = true;
            mSourceHint    = "Detected: LUSID package";
        } else {
            mSourceHint = "Directory has no scene.lusid.json — not a LUSID package";
        }
    }
}

// ── Path helpers ──────────────────────────────────────────────────────────────

std::string App::resolveProjectPath(const std::string& relPath) const {
    if (relPath.empty()) return "";
    return (fs::path(mProjectRoot) / relPath).string();
}

std::string App::findCultTranscoder() const {
    // Try new root-cmake build location first, then standalone build fallback
    std::vector<std::string> candidates = {
        resolveProjectPath("build/cult_transcoder/cult-transcoder"),
        resolveProjectPath("cult_transcoder/build/cult-transcoder"),
    };
#ifdef _WIN32
    for (auto& c : candidates) c += ".exe";
#endif
    for (const auto& c : candidates) {
        if (fs::exists(c)) return c;
    }
    return "";  // not found — caller must handle
}

std::string App::transcodeOutputPath(const std::string& admPath) const {
    fs::path p(admPath);
    std::string stem = p.stem().string();
    return resolveProjectPath(
        "processedData/stageForRender/" + stem + ".lusid.json");
}

// ── Log helpers ───────────────────────────────────────────────────────────────

void App::appendEngineLog(const std::string& text, ImVec4 color) {
    mEngineLog.push_back({color, text});
    if (mEngineLog.size() > 2000)
        mEngineLog.pop_front();
}

void App::appendTcLog(const std::string& line) {
    // Called from SubprocessRunner background thread — needs mutex.
    ImVec4 color = {0.85f, 0.85f, 0.85f, 1.f};
    std::string lower = line;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    if (lower.find("error") != std::string::npos)
        color = {1.f, 0.35f, 0.35f, 1.f};
    else if (lower.find("warn") != std::string::npos)
        color = {1.f, 0.8f, 0.2f, 1.f};
    else if (line.size() > 3 && line.substr(0, 4) == "[ok]")
        color = {0.3f, 0.9f, 0.3f, 1.f};

    std::lock_guard<std::mutex> lock(mTcLogMutex);
    mTcLog.push_back({color, line});
    if (mTcLog.size() > 2000)
        mTcLog.pop_front();
}

// ── State display helpers ─────────────────────────────────────────────────────

const char* App::stateName(AppState s) {
    switch (s) {
        case AppState::Idle:        return "IDLE";
        case AppState::Transcoding: return "TRANSCODING";
        case AppState::Running:     return "RUNNING";
        case AppState::Paused:      return "PAUSED";
        case AppState::Error:       return "ERROR";
    }
    return "UNKNOWN";
}

ImVec4 App::stateColor(AppState s) {
    switch (s) {
        case AppState::Idle:        return {0.55f, 0.55f, 0.55f, 1.f};
        case AppState::Transcoding: return {1.f,   0.8f,  0.f,   1.f};
        case AppState::Running:     return {0.2f,  0.9f,  0.2f,  1.f};
        case AppState::Paused:      return {1.f,   0.6f,  0.1f,  1.f};
        case AppState::Error:       return {1.f,   0.3f,  0.3f,  1.f};
    }
    return {1.f, 1.f, 1.f, 1.f};
}
